# Long ISO timestamps are easier to read and less ambiguous.
timestamp_format long-iso

# Retention policy.
snapshot_preserve 14d 8w 12m
snapshot_preserve_min 48h

# /var/backups is the Btrfs filesystem mount point.
volume /var/backups/
	subvolume local/system/mirror/
		snapshot_create onchange
		snapshot_dir local/system/snapshots/
		snapshot_name system
